id: P005398
initial_creation_type: ocr
source_metadata:
  id: bdr:W8LS19093
  title: མི་རིགས་ས་ཁོངས་རང་སྐྱོང་བཅའ་ཁྲིམས་བསླབ་དེབ།
  author: ''
  volumes:
    278d787b15aa41768b46c181915e7216:
      image_group_id: I8LS19095
      title: ''
      volume_number: 1
      total_pages: 218
      base_file: v001.txt
